# Generated by Django 5.2.4 on 2025-07-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_category_softwarekit_delete_tblform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/category/'),
        ),
    ]
